wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710164459.0
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 51
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 51
      - 53
      - 55
      - 103
      3:
      - 7
      - 23
      4: 3.10.12
      5: 0.16.4
      6: 4.38.2
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train/loss_step
      5: 1
      6:
      - 1
    - 1: train/acc_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: valid/loss_step
      5: 1
      6:
      - 1
    - 1: valid/loss_epoch
      5: 1
      6:
      - 1
    - 1: valid/acc
      5: 1
      6:
      - 1
    - 1: valid/precision_macro
      5: 1
      6:
      - 1
    - 1: valid/recall_macro
      5: 1
      6:
      - 1
    - 1: valid/precision_micro
      5: 1
      6:
      - 1
    - 1: valid/recall_micro
      5: 1
      6:
      - 1
    - 1: valid/f1
      5: 1
      6:
      - 1
model_name:
  desc: null
  value: google/bert_uncased_L-2_H-128_A-2
lr:
  desc: null
  value: 0.01
